# Generated by Django 4.2.2 on 2023-07-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutbolMundial', '0002_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='profesion',
        ),
    ]
